### ISSUE TITLE
Plugin version 1.18 (Apr '22 update) does not parse grammars with new caseInsensitive option at lexer level

### ISSUE THREAD

**Issue by kaby76** [antlr/intellij-plugin-v4#549] opened 2022-05-05 10:45 UTC
Support for case insensitive grammars was introduced in Antlr version 4.10 (the right thing to do I might add). With these grammars, one can have `options { caseInsensitive = ...; }` at the grammar-level (just after the grammar declaration) or at the lexer rule level (just after the LHS lexer rule name and before the colon of a rule).

Unfortunately, grammars with the lexer rule level option cause the Antlr4 lexer within the plugin to fail because the ';' in the `options { }` changes the state of the lexer to assume the charset '[' is not a charset but a rule "argument". The lexer is implemented with state information to destinguish between '[' starts a lex.

(Note, I could go into how the current design could be implemented with parser state information, but that is for another day, and is likely to be considered "haram" by others--as one can easily do it wrong. Antlr goes way out of its way with `mode` and lexer state information to implement parser state dependent lexing. Incorporating parser state would be cleaner.)

The plugin does not output any text error messages saying the parse failed, and I only knew that there is a problem in the parse if I looked closely at the lexer rule containing the `option { }` and a charset: the opening '[' of a charset of the lexer rule would be underlined with a small red line. I found out this problem because trgen uses a similar Antlr4 grammar, and failed to generate a driver for the parser. An analysis of the problem is [here](https://github.com/antlr/grammars-v4/pull/2576#issuecomment-1118071596).

To reproduce the problem, open the modified [php grammar Ivan is working on](https://github.com/KvanTTT/grammars-v4/tree/e37bed7a21218fcd1d1bb47492bf4e8e4c329400/php), and open in Intellij the PhpLexer.g4 file, the go to [this line](https://github.com/KvanTTT/grammars-v4/blob/e37bed7a21218fcd1d1bb47492bf4e8e4c329400/php/PhpLexer.g4#L353). There should be a tiny red line under the '[' of the charset.

**Comment by parrt** [comment] 2022-05-13 19:12
So the tool gives an error but we're not highlighting in grammar view?

**Comment by kaby76** [comment] 2022-05-13 19:37
Actually, it highlights a grammar well because the plugin recovers from the parse error and still gives a pretty good tree. You wouldn't even know that the parse fails, except for a very tiny red underscore under a '['-character for the lexer char set that happened to follow. I updated the grammar [here](https://github.com/antlr/grammars-v4/tree/master/antlr/antlr4), but the only important difference is the lexer base class.

**Comment by parrt** [comment] 2022-05-13 20:14
Oh, ok, what's the issue?  That plugin should look for case sens option and use that during interp mode?  Can interp even do that yet? Not sure @kvanTTT did that as part of his update. can't remember.

**Comment by kaby76** [comment] 2022-05-13 22:44
Sorry, [this valid Antlr4.10 grammar for PHP](https://github.com/antlr/grammars-v4/tree/master/php) does not parse in Intellij v 1.18-2021. To reproduce, clone https://github.com/antlr/grammars-v4.git , then open Intellij on the grammars-v4/php directory, then open file PhpLexer.g4 at line 353. You will see a red underscore under '[' of the lexer char set for the rule. That indicates a parse error. The same thing happened with my parser for Trash until I made fixed the [Antlr4 base class](https://github.com/antlr/grammars-v4/blob/3508a0ac7c4baaa64c13de5cfd05f536653f2004/antlr/antlr4/Java/LexerAdaptor.java). The Intellij Antlr plugin uses the [same Antlr4 lexer class members](https://github.com/antlr/intellij-plugin-v4/blob/3e8a8ea3219a0b5d544fdc464bdc043801a25261/src/main/antlr/org/antlr/intellij/plugin/parser/ANTLRv4Lexer.g4#L50) from the lexer base class (i.e., grammars-v4/php is "target agnostic", the plugin grammar for Antlr4 is not. The semantic predicates do not completely work for this grammar for PHP.

**Comment by KvanTTT** [comment] 2022-05-14 10:47
It definitely should be fixed in the next version.

**Comment by parrt** [comment] 2022-05-14 17:16
If anybody has suggestions for how to fix in the plug-in, please let me know since I’m in the middle of something else at the moment

**Closed** 2022-05-14 23:28 UTC
Labels: bug, comp:grammar-editor

**Comment by parrt** [comment] 2022-05-17 16:51
Confirmed. Now parses fine. Thanks, @KvanTTT !!

**Comment by parrt** [comment] 2022-05-17 16:54
Try this one. I'll release soon.

[antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip](https://github.com/antlr/intellij-plugin-v4/files/8710163/antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip)
