### ISSUE TITLE
deprecation exception in IntelliJ

### ISSUE THREAD

**Issue by tbabczynski** [antlr/intellij-plugin-v4#710] opened 2024-08-08 17:07 UTC
The 2024.2 IntelliJ throws the following exception:
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.TestRuleAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by bjansen** [comment] 2024-08-09 07:35
Duplicate of https://github.com/antlr/intellij-plugin-v4/issues/696

**Closed by bjansen** 2024-08-09 07:35 UTC
Labels: duplicate
