### ISSUE TITLE
RuntimeException: set is empty

### ISSUE THREAD

**Issue by geniot** [antlr/intellij-plugin-v4#462] opened 2021-06-26 12:49 UTC
When trying to change a rule:
TEXT : ~['[']+ ;
trying different variants.

java.lang.RuntimeException: set is empty
	at org.antlr.v4.runtime.misc.IntervalSet.getMaxElement(IntervalSet.java:421)
	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:169)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
	at org.antlr.v4.runtime.atn.ATNSerializer.getSerializedAsChars(ATNSerializer.java:605)
	at org.antlr.v4.tool.Grammar.createLexerInterpreter(Grammar.java:1313)
	at org.antlr.intellij.plugin.parsing.ParsingUtils.parseText(ParsingUtils.java:206)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.lambda$parseText$1(ANTLRv4PluginController.java:438)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$6(BackgroundTaskUtil.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$computeInBackgroundAndTryWait$7(BackgroundTaskUtil.java:169)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by bjansen** [comment] 2021-06-28 08:42
Hi,

Could you check if the issue is the same as either #316 or maybe https://github.com/antlr/antlr4/issues/2498 ?

**Comment by geniot** [comment] 2021-07-06 20:29
The problem with this and similar antlr4 exceptions is IDEA's memory usage. Suddenly it grows to 5Gb on my computer. And IDEA becomes irresponsive. I have to restart it. Is there a way to limit memory usage by ANTLR? Maybe set Xmx when running the parse thread.

**Comment by bjansen** [comment] 2021-07-08 09:35
I can't think of a way to do this. Everything runs in the same process (the IDE), and the heap is shared so there's no way to add limits to a given thread, and no way to set `Xmx` dynamically.

The plugin already tries to detect similar problems (bad grammars that cause the interpreter to run in a loop and use all the memory), and stops the interpreter after a while. I guess your problem is somehow different. 

Did the IDE produce thread dumps when the problem occurred? You can find them in `Help > Show Logs`. They could help us understand what's happening, and maybe the plugin could detect this problem too.

**Comment by bjansen** [comment] 2021-07-08 09:36
BTW if you could provide a simple grammar to reproduce the problem, that would be great.

**Comment by parrt** [comment] 2022-02-20 18:40
Hi @geniot  any more information you can give us?   I tried playing around and could not get an exception I did manage to get an error message with an empty set `[]+`:

```
error(174): /Users/parrt/tmp/T.g4:6:8: string literals and sets cannot be empty: []
```

with your snippet, I get this warning when I generate code:

```
warning(180): /Users/parrt/tmp/T.g4:6:8: chars '\'' used multiple times in set ['[']
```

**Comment by KvanTTT** [comment] 2022-02-20 20:11
Most likely it already has been fixed in https://github.com/antlr/antlr4/pull/3310

**Comment by geniot** [comment] 2022-02-20 21:25
Hi @parrt , 
sorry, I can't give you more information or test an updated version. I have moved to other projects.

**Closed** 2022-02-20 22:46 UTC
Labels: bug
