### ISSUE TITLE
idea2024.1 error

### ISSUE THREAD

**Issue by 954615673** [antlr/intellij-plugin-v4#705] opened 2024-06-06 01:51 UTC
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.ConfigureANTLRAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by bjansen** [comment] 2024-06-06 03:22
Duplicate of #696

**Closed by bjansen** 2024-06-06 03:22 UTC
