### ISSUE TITLE
[\p{Emoji}]+ is capturing numbers

### ISSUE THREAD

**Issue by dleuck** [antlr/intellij-plugin-v4#389] opened 2020-02-08 08:57 UTC
The lexer patern [\p{Emoji}]+ is matching numbers. See screenshot. Note that it correctly ignores alpha chars.

![Screen Shot 2020-02-08 at 5 54 15 PM](https://user-images.githubusercontent.com/815078/74082348-6058b000-4a9c-11ea-9556-6442d8c0b34a.png)

**Comment by bjansen** [comment] 2020-02-08 09:45
I believe this is caused by the ANTLR tool, not the IntelliJ plugin. I get the same result in the CLI:

```antlr
grammar emoji;

tag: Identifier+;

Identifier: [\p{Emoji}]+;

WHITESPACE: [ \t\n\r]+ -> channel(HIDDEN);
ERRCHAR: . -> channel(HIDDEN);
```
```
10:42 bastien@mbp2:emoji$ grun emoji tag -tokens
😝🤓😒🙁123
[@0,0:6='😝🤓😒🙁123',<Identifier>,1:0]
[@1,7:7='\n',<WHITESPACE>,channel=1,1:7]
[@2,8:7='<EOF>',<EOF>,2:0]
```

@parrt or @sharwell could you please confirm it's a bug, and maybe transfer the issue to antlr/antlr?

**Comment by dleuck** [comment] 2020-02-08 11:46
I think you are right. A [response on StackExchange](https://stackoverflow.com/questions/60125337/antlr-lexer-patern-pemoji-is-matching-numbers) pointed out line 341 in org.antlr.v4.unicode.UnicodeDataTemplateController:

`UnicodeSet emojiRKUnicodeSet = new UnicodeSet("[\\p{GCB=Regional_Indicator}\\*#0-9\\u00a9\\u00ae\\u2122\\u3030\\u303d]");`

I wonder why the *#0-9 sequence is included in this set definition. It seems random.

**Comment by bjansen** [comment] 2020-02-11 08:24
OK, so from what I understand: "it's not a bug, it's a feature" :).
I'm closing the issue, but feel free to reopen it if you disagree.

**Closed by bjansen** 2020-02-11 08:24 UTC
