### ISSUE TITLE
Generating images of parse tree

### ISSUE THREAD

**Issue by tkmitchell** [antlr/intellij-plugin-v4#358] opened 2019-06-08 16:05 UTC
I am using Intellij 2018.3.6 and latest antlr and plugin. I can select the popup menu item for export to image and select a location, but it does not generate the file. Is this a known problem? I cannot find any errors being recorded anywhere.

**Comment by bjansen** [comment] 2019-06-21 08:21
Could you go to `Help > Show Logs in explorer` and attach idea.log please?

**Comment by tkmitchell** [comment] 2019-06-22 04:51
I am on the road now. When I get back home I can do that.

**Comment by clojj** [comment] 2019-06-25 08:59
I can't reproduce this in 2019.1 ...the png gets exported correctly

**Comment by tkmitchell** [comment] 2019-06-27 02:35
I was having trouble with the 2019 version and the plugin, so I downgraded to the 2018 version. I will upgrade to the 2019 and the 1.10 versions and try them.

**Comment by bjansen** [comment] 2019-06-27 06:44
Still, if you are able to find the logs from when the issue happened, this could help me pinpoint what happened. Thanks.

**Comment by bjansen** [comment] 2020-02-17 09:45
I'm closing the issue since it looks like it's not happening anymore, but feel free to reopen it.

**Closed by bjansen** 2020-02-17 09:45 UTC
Labels: bug, status:cannot-reproduce
