### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by sglaser** [antlr/intellij-plugin-v4#321] opened 2018-01-02 06:55 UTC
Trying to preview a grammar for SystemRDL 2.0 (untested -- work in progress).

(files renamed to append .txt so that GitHub will upload them).

[reset_naming.rdl.txt](https://github.com/antlr/intellij-plugin-v4/files/1596955/reset_naming.rdl.txt)
[SystemRDL2.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/1596956/SystemRDL2.g4.txt)

I'm trying to parse the reset_naming.rdl file. In an attempt to figure things out, I'm also trying parts of the file directly in the input area of the Antlr Preview.

I'm not sure exactly what I did to create the error -- I'm getting frequent errors that appear to be the same.

It may be related, but one of my current issues is the inability of this grammar to accept single letter identifiers. Two or more characters works fine (whether or not the first character is a backslash -- backslash preceding an identifier is the SystemRDL way to using an identifier that would otherwise the a reserved word).

IDE CLion 2017.3.1
Build #CL-173.4127.32, built on December 26, 2017
Licensed to Steve Glaser
Subscription is active until November 2, 2018
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

null
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.InputPanel.createPreviewEditor(InputPanel.java:272)
	at org.antlr.intellij.plugin.preview.InputPanel.selectFileEvent(InputPanel.java:264)
	at org.antlr.intellij.plugin.preview.InputPanel$4.actionPerformed(InputPanel.java:172)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by bjansen** [comment] 2018-11-11 12:00
Duplicate of #305, fixed in #343

**Comment by parrt** [comment] 2018-12-18 21:57
Fixed per @bjansen

**Closed by parrt** 2018-12-18 21:57 UTC
