### ISSUE TITLE
crash/freeze with non-greedy token

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/intellij-plugin-v4#333] opened 2018-06-18 15:13 UTC
Happens with IntelliJ CE 2018.1.5 and plugin 1.8.4 macosx 10.13.5

How to reproduce:
open the attached grammar in IntelliJ
right click on 'attribute' rule, select 'Test rule attribute'
In input window, paste: name="value" -> OK
Now delete the last double-quote -> freeze
Alternately, type: name= -> OK
Now type a double-quote -> freeze

[crash.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/2111817/crash.g4.txt)

**Comment by AlexBono97** [comment] 2018-09-23 14:52
I confirm the same issue happens if you try using :: . It seems when pressing Shift + another key, it generates a big problem with memory

**Comment by bjansen** [comment] 2018-12-19 22:07
I think it's a bug in ANTLR itself, not in the IntelliJ plugin. I can reproduce the problem using the command line tools:

```
$ antlr crash.g4
warning(146): crash.g4:15:0: non-fragment lexer rule OTHER can match the empty string
warning(125): crash.g4:26:6: implicit definition of token LCURL in parser
warning(125): crash.g4:26:23: implicit definition of token RCURL in parser
$ javac crash*.java
$ grun crash attribute crash.txt
^CException in thread "main" 23:02 bastien@mbp2:src$ grun crash attribute crash.txt
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.antlr.v4.runtime.CommonTokenFactory.create(CommonTokenFactory.java:70)
	at org.antlr.v4.runtime.CommonTokenFactory.create(CommonTokenFactory.java:16)
	at org.antlr.v4.runtime.Lexer.emit(Lexer.java:245)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:156)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
	at org.antlr.v4.runtime.BufferedTokenStream.fill(BufferedTokenStream.java:485)
	at org.antlr.v4.gui.TestRig.process(TestRig.java:174)
	at org.antlr.v4.gui.TestRig.process(TestRig.java:166)
	at org.antlr.v4.gui.TestRig.main(TestRig.java:119)
```

Yourkit shows that 4 million instances of `ErrorNodeImpl` and `CommonToken` were instantiated.

@parrt it looks like the parser is stuck in a loop or something like that

**Comment by parrt** [comment] 2018-12-19 22:44
The error is actually in the grammar, as shown by the warning:

```
warning(146): crash.g4:15:0: non-fragment lexer rule OTHER can match the empty string
```

Closing.

**Closed by parrt** 2018-12-19 22:44 UTC
Labels: bug, comp:grammar-editor
