### ISSUE TITLE
PluginException when using 1.23.1 in Intellij 2024.2.2

### ISSUE THREAD

**Issue by SingingBush** [antlr/intellij-plugin-v4#717] opened 2024-09-22 12:30 UTC
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.UniquifyRuleRefs' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by ben-509** [comment] 2024-09-23 21:56
Dupe of #696

**Comment by swnck** [comment] 2024-10-04 00:20
Please release the current 1.23.2 because nothing works with the current 1.23.1 version.

**Closed** 2024-10-06 09:49 UTC
