### ISSUE TITLE
Feature Request - Test Lexer Rules

### ISSUE THREAD

**Issue by nmz787** [antlr/intellij-plugin-v4#430] opened 2021-01-13 03:15 UTC
Lexer rules can't be tested, but having them work correctly is fundamental to having a parser rule work.

I was able to code Python unit tests for the lexer rules, to aid in my development and debug:
https://gist.github.com/nmz787/cf98aa465a4d071a937cf74788687a54

but it was quite unexpected that the visual plugin couldn't do this.

**Comment by bjansen** [comment] 2021-01-13 09:04
I think #417 is the same request as yours? If there was a new tab in the right part of the preview, showing the list of tokens that were lexed, would that be enough?

**Comment by bjansen** [comment] 2021-03-04 21:08
@nmz787 is it something like this you're looking for? https://github.com/antlr/intellij-plugin-v4/issues/417#issuecomment-766168222

**Comment by bjansen** [comment] 2021-11-02 19:54
Closing as duplicate of #417

**Closed by bjansen** 2021-11-02 19:54 UTC
Labels: duplicate, feature-request

**Comment by nmz787** [comment] 2021-11-29 21:41
I don't think #417 is the same thing. #417 wants to see tokens associated with a specific parser rule. This ticket (430) is about wanting lexer tokens, without having written a parser.
