### ISSUE TITLE
[\p{Lu}] => Invalid escape sequence in Jetbrains Rider

### ISSUE THREAD

**Issue by kazaak** [antlr/intellij-plugin-v4#449] opened 2021-04-10 22:49 UTC
I've installed this plugin for Rider 2021.1.1, and not able to make much of a go of it:

```
grammar Dummy ;

hi : START ;

START : [\p{Lu}] ;
```
Building the project produces the error `  Dummy.g4(5, 9): [AC0156] invalid escape sequence.`  It works fine in antlr4 from the command line (the command line is antlr 4.7.2 from a debian package; antlr in rider is 4.9.1, as reported in Tools -> Configure Antlr).

The generate option from tools-> generate antlr recognizer work without issue.  Generating without specifying "CSharp" produces Java which correctly recognizes the difference in tool versions as described, but works on the generated grammar as well as it should, other things being equal:

```
$ grun Dummy hi -tree -tokens
Warning: TestRig moved to org.antlr.v4.gui.TestRig; calling automatically
ANTLR Tool version 4.9.1 used for code generation does not match the current runtime version 4.7.2ANTLR Tool version 4.9.1 used for code generation does not match the current runtime version 4.7.2
A
line 1:0 token recognition error at: '\n'
line 2:1 token recognition error at: '\n'
[@0,1:1='A',<START>,2:0]
[@1,3:2='<EOF>',<EOF>,3:0]
(hi A)
```

I'm able to work around this by using the command line (which is more natural for me anyway, vim plugin of rider notwithstanding).

**Comment by kazaak** [comment] 2021-04-14 13:33
This was plainly my own issue.  This plugin is fine.  It requires the Antlr4.Runtime.Standard nuget package where I was using the Antlr4.Runtime nuget package.  I didn't see that I needed to install additional nuget packages, but added the Antlr4.Runtime to fix errors.  It sorta fixed them :)

**Comment by bjansen** [comment] 2021-10-05 18:54
Closing, since you said it's likely not an issue caused by the plugin.

**Closed by bjansen** 2021-10-05 18:54 UTC
