### ISSUE TITLE
PluginException: `ActionUpdateThread.OLD_EDT` is deprecated - Intellij 2024.2

### ISSUE THREAD

**Issue by ssamayoa** [antlr/intellij-plugin-v4#709] opened 2024-08-08 12:41 UTC
I just updated to Intellij 2024.2 and get this error:

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.GenerateParserAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

I did a smoke test with "ANTLR Preview" and looks that everything is fine so seems, as the text also suggests, a preventive exception.

**Comment by bjansen** [comment] 2024-08-08 15:13
Duplicate of https://github.com/antlr/intellij-plugin-v4/issues/696

**Closed** 2024-08-08 15:13 UTC
Labels: duplicate
