### ISSUE TITLE
Incorrect "no viable alternative at input" warning

### ISSUE THREAD

**Issue by sergio-castro** [antlr/intellij-plugin-v4#379] opened 2019-11-22 20:56 UTC
This is my setting: I have a simple grammar which a parser and a lexer in distinct files.
This is the code of the parser:

```
parser grammar DummyParser;
options { tokenVocab='lexerparsersplit/DummyLexer'; }

@header {
    package lexerparsersplit;
}

r : ID;
```

And this is the code of the lexer:

```
lexer grammar DummyLexer;

@header {
    package lexerparsersplit;
}

ID : [a-z]+ ;
WS : [ \t\r\n]+ -> skip ;
```

In the lexer editor, there is an annoying error message in the ID declaration line, pointing to the '[' symbol saying: 

> no viable alternative at input '['

I do not believe the code is incorrect since I can generate the lexer and parser classes without problems and also execute the test rig successfully. So I believe this should be a bug in the IntelliJ plugin showing a wrong warning. Is this a possibility ?

**Comment by bjansen** [comment] 2019-11-22 21:33
It looks like a duplicate of #374, which I fixed recently.

**Comment by sergio-castro** [comment] 2019-11-22 22:02
Thanks for the quick answer @bjansen. 
Will the fix be released soon ? I think I am already using the latest recent version of the plugin.

**Comment by bjansen** [comment] 2019-11-23 09:35
Yes I'll schedule a release in the next days, I have to fix a couple other bugs first.

**Comment by bjansen** [comment] 2019-11-23 19:26
Fixed by #374

**Closed by bjansen** 2019-11-23 19:26 UTC
Labels: bug, duplicate

**Comment by bjansen** [comment] 2019-11-23 20:01
I just released 1.12, you can check for updates right now :)

**Comment by sergio-castro** [comment] 2019-11-23 22:21
Thanks a lot @bjansen !! The problem is fixed now.

**Comment by sergio-castro** [comment] 2019-11-23 22:27
btw @bjansen , just one last question regarding the example that I posted above. In the definition of the `r` rule, `ID` is shown highlighted in yellow by IntelliJ, and I see a warning message that says: 

> warning(125): ... implicit definition of token ID in parser.

Is this warning a bug since `ID` is actually defined in the Lexer file ? is there a way to get rid of this warning ? Thanks!

**Comment by bjansen** [comment] 2019-11-24 08:58
Did you put both grammars in the same directory?

**Comment by bjansen** [comment] 2019-11-24 09:09
I can make the warning disappear in two cases:
* If both grammars are in the same directory and `tokenVocab='DummyLexer'`
* Or, if `DummyLexer.g4` in is a subdirectory named `lexerparsersplit` and `tokenVocab='lexerparsersplit/DummyLexer'`

**Comment by sergio-castro** [comment] 2019-11-24 10:41
Hi Bastien! yes, both the lexer and the parser live in the same directory: `lexerparsersplit`, which is also the package name of the generated classes, hence the header with the `package lexerparsersplit;` declaration in both files.
I am curious about which are the recommended best practices if I want to split my grammar in a parser and a lexer file. 
If I leave them in a directory (as they are now) and replace, in the options of the parser, `tokenVocab='lexerparsersplit/DummyLexer';` by just `tokenVocab=DummyLexer;` the warning in the IDE disappears, but when I try to build the project (I am using the ANTLR Gradle plugin) I see the following errors:

> error(160): lexerparsersplit/DummyParser.g4:3:21: cannot find tokens file ...../build/generated-src/antlr/main/DummyLexer.tokens
> warning(125): lexerparsersplit/DummyParser.g4:9:4: implicit definition of token ID in parser

Locating one or both of the files in the root directory (I think your second suggestion is to put the parser there and the lexer in the folder?) is not a good option because I have other grammars in the same project that I would prefer to keep in separate folders.

But I guess mine is probably a pretty common problem, so I just would like to know which is the recommended project layout for this setting and I will try to stick to it. I guess I could also leave with the warning in the IDE but would love to know your feedback first.
Thanks.

**Comment by bjansen** [comment] 2019-11-24 20:06
OK, actually I have the same problem in another project of mine, which I "solved" like this:
```antlr
// Use this when working with the IntelliJ plugin
//options { tokenVocab=PebbleLexer; }

// Use this when working with Gradle
options { tokenVocab='com/github/bjansen/pebble/parser/PebbleLexer'; }
```
Every time I work on the grammar, I swap the commented line with the other.

I guess there are lots of improvements to be made to support Maven and Gradle projects (like #306 and #314), but I still have to take time to fully understand what's missing and how to implement it :)

The plugin itself doesn't need this ugly workaround, so maybe you can replicate what's done:
* everything is in `src/main/antlr/org/antlr/intellij/plugin/parser`
* the parser is configured like this:
```antlr
options {
	tokenVocab=ANTLRv4Lexer;
}
```
* the build is configured like this:
```groovy
generateGrammarSource {
    arguments += [
            "-package", "org.antlr.intellij.plugin.parser",
            "-Xexact-output-dir"
    ]
}
```

I don't know if it's compatible with multiple grammars in the same project though.

**Comment by sergio-castro** [comment] 2019-11-24 21:02
I think that a better way to fix this may be to introduce the concept of `package` as a first-class construct in the grammar files, instead of relying on the content of the @header to declare it, or to pass the package as an argument from the command line (the later will not work if there are distinct grammars in the same project, because everything will end-up in the same package).

So the `@header` section in my sample could be replaced by something in the style of: 
`@package 'lexerparsersplit';`
The fact that there is even a command line option to specify a package may be a symptom that what I suggest may be missing as a first-class construct in the grammar.

Cheers!
