### ISSUE TITLE
NPE in version 14.1.4 while editing grammar

### ISSUE THREAD

**Issue by malduarte** [antlr/intellij-plugin-v4#214] opened 2015-08-18 19:23 UTC
When I open the following grammar from http://www.alexecollins.com/antlr4-and-maven-tutorial/

```
grammar Field;

field:
    name=Name NL
    (points NL)+
    (burial NL)+
    EOF;

points: treasure=Name WS 'scores' WS value=Int WS 'points';
burial: treasure=Name WS 'is' WS 'buried' WS 'at' WS at=location ;
location: x=Int ',' y=Int;

Name: '"' ('A'..'Z' | 'a'..'z' | ' ')+ '"' ;
Int: ('0'..'9')+;

WS: (' ' | '\t')+;
NL:  '\r'? '\n';
```

I have this NPE

```
null
java.lang.NullPointerException
	at org.antlr.intellij.plugin.preview.InputPanel.clearGrammarHighlighters(InputPanel.java:461)
	at org.antlr.intellij.plugin.profiler.ProfilerPanel.mouseEnteredGrammarEditorEvent(ProfilerPanel.java:99)
	at org.antlr.intellij.plugin.ANTLRv4PluginController.mouseEnteredGrammarEditorEvent(ANTLRv4PluginController.java:288)
	at org.antlr.intellij.plugin.ANTLRv4PluginController$GrammarEditorMouseAdapter.mouseClicked(ANTLRv4PluginController.java:521)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.b(EditorImpl.java:5650)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5580)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by parrt** [comment] 2015-11-01 18:18
Hm...i'm trying to track down some null ptrs but I can't reproduce this one. I loaded from disk with no problem. saved no problem. quit, autoreload. no problem. sorry!

**Comment by parrt** [comment] 2015-11-01 18:29
seems similar to #213

**Comment by parrt** [comment] 2015-11-01 18:37
Do you still have the log file? Under Help > show log file.

**Comment by parrt** [comment] 2015-11-01 20:43
Duplicate of #203

**Closed by parrt** 2015-11-01 20:43 UTC
Labels: bug, status:cannot-reproduce
